import type { SpacingProps } from './spacing';

/**
 * Runtime allowlist — must stay in sync with {@link SpacingProps}.
 * Used to separate style-system props from DOM passthrough on `Box`.
 */
export const SPACING_STYLE_PROP_KEYS = new Set<string>([
  'w',
  'h',
  'minW',
  'maxW',
  'minH',
  'maxH',
  'm',
  'mt',
  'mr',
  'mb',
  'ml',
  'mx',
  'my',
  'p',
  'pt',
  'pr',
  'pb',
  'pl',
  'px',
  'py',
  'flex',
  'flexGrow',
  'flexShrink',
  'flexBasis',
  'flexDirection',
  'flexWrap',
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'textAlign',
  'gap',
  'gridTemplateColumns',
  'gridTemplateRows',
  'gridColumn',
  'gridRow',
  'gridArea',
  'alignItems',
  'justifyContent',
  'alignContent',
  'justifyItems',
  'alignSelf',
  'justifySelf',
  'backgroundColor',
  'color',
  'border',
  'borderRadius',
  'boxShadow',
  'cursor',
  'opacity',
  'zIndex',
  'className',
  'style',
] satisfies (keyof SpacingProps)[]);
